{% set name = "pysmt" %}
{% set version = "0.9.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pysmt/pysmt/archive/v{{ version }}.tar.gz
  sha256: d69561abccd089c23352a6862b3939574d47d37ed82a5d7dce75127437c06032

build:
  entry_points:
    - pysmt-install = pysmt.cmd.install:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - pysmt
  commands:
    - pip check
    - pysmt-install --help
  requires:
    - pip

about:
  home: http://www.pysmt.org
  summary: A library for SMT formulae manipulation and solving
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  dev_url: https://github.com/pysmt/pysmt

extra:
  recipe-maintainers:
    - BastianZim
