{% set name = "pysmt" %}
{% set version = "0.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pysmt/pysmt/archive/v{{ version }}.tar.gz
  sha256: d0315f33a35bf9469c6106531f71cd60f76a595aa982db5e71c7df230e6526c1

build:
  entry_points:
    - pysmt-install = pysmt.cmd.install:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - pysmt
  commands:
    - pip check
    - pysmt-install --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://www.pysmt.org
  summary: A library for SMT formulae manipulation and solving
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  dev_url: https://github.com/pysmt/pysmt

extra:
  recipe-maintainers:
    - BastianZim
